//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSE445_Project5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WordFilter", ReplyAction="http://tempuri.org/IService1/WordFilterResponse")]
        string WordFilter(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WordFilter", ReplyAction="http://tempuri.org/IService1/WordFilterResponse")]
        System.Threading.Tasks.Task<string> WordFilterAsync(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Number2Words", ReplyAction="http://tempuri.org/IService1/Number2WordsResponse")]
        string Number2Words(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Number2Words", ReplyAction="http://tempuri.org/IService1/Number2WordsResponse")]
        System.Threading.Tasks.Task<string> Number2WordsAsync(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRandomRecipe", ReplyAction="http://tempuri.org/IService1/GetRandomRecipeResponse")]
        string GetRandomRecipe();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRandomRecipe", ReplyAction="http://tempuri.org/IService1/GetRandomRecipeResponse")]
        System.Threading.Tasks.Task<string> GetRandomRecipeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWineDescription", ReplyAction="http://tempuri.org/IService1/GetWineDescriptionResponse")]
        string GetWineDescription(string wine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWineDescription", ReplyAction="http://tempuri.org/IService1/GetWineDescriptionResponse")]
        System.Threading.Tasks.Task<string> GetWineDescriptionAsync(string wine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AnalyzeRecipe", ReplyAction="http://tempuri.org/IService1/AnalyzeRecipeResponse")]
        string AnalyzeRecipe(string recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AnalyzeRecipe", ReplyAction="http://tempuri.org/IService1/AnalyzeRecipeResponse")]
        System.Threading.Tasks.Task<string> AnalyzeRecipeAsync(string recipe);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CSE445_Project5.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CSE445_Project5.ServiceReference1.IService1>, CSE445_Project5.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string WordFilter(string input) {
            return base.Channel.WordFilter(input);
        }
        
        public System.Threading.Tasks.Task<string> WordFilterAsync(string input) {
            return base.Channel.WordFilterAsync(input);
        }
        
        public string Number2Words(string number) {
            return base.Channel.Number2Words(number);
        }
        
        public System.Threading.Tasks.Task<string> Number2WordsAsync(string number) {
            return base.Channel.Number2WordsAsync(number);
        }
        
        public string GetRandomRecipe() {
            return base.Channel.GetRandomRecipe();
        }
        
        public System.Threading.Tasks.Task<string> GetRandomRecipeAsync() {
            return base.Channel.GetRandomRecipeAsync();
        }
        
        public string GetWineDescription(string wine) {
            return base.Channel.GetWineDescription(wine);
        }
        
        public System.Threading.Tasks.Task<string> GetWineDescriptionAsync(string wine) {
            return base.Channel.GetWineDescriptionAsync(wine);
        }
        
        public string AnalyzeRecipe(string recipe) {
            return base.Channel.AnalyzeRecipe(recipe);
        }
        
        public System.Threading.Tasks.Task<string> AnalyzeRecipeAsync(string recipe) {
            return base.Channel.AnalyzeRecipeAsync(recipe);
        }
    }
}
