//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItPages.spoonacularService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recipe", Namespace="http://schemas.datacontract.org/2004/07/spoonacularService")]
    [System.SerializableAttribute()]
    public partial class Recipe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string summaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string summary {
            get {
                return this.summaryField;
            }
            set {
                if ((object.ReferenceEquals(this.summaryField, value) != true)) {
                    this.summaryField = value;
                    this.RaisePropertyChanged("summary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="spoonacularService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchRecipesByIngredients", ReplyAction="http://tempuri.org/IService1/SearchRecipesByIngredientsResponse")]
        TryItPages.spoonacularService.Recipe[] SearchRecipesByIngredients(string ingredients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchRecipesByIngredients", ReplyAction="http://tempuri.org/IService1/SearchRecipesByIngredientsResponse")]
        System.Threading.Tasks.Task<TryItPages.spoonacularService.Recipe[]> SearchRecipesByIngredientsAsync(string ingredients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecipeSummaryById", ReplyAction="http://tempuri.org/IService1/GetRecipeSummaryByIdResponse")]
        TryItPages.spoonacularService.Recipe GetRecipeSummaryById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRecipeSummaryById", ReplyAction="http://tempuri.org/IService1/GetRecipeSummaryByIdResponse")]
        System.Threading.Tasks.Task<TryItPages.spoonacularService.Recipe> GetRecipeSummaryByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MenuAutoComplete", ReplyAction="http://tempuri.org/IService1/MenuAutoCompleteResponse")]
        TryItPages.spoonacularService.Recipe MenuAutoComplete(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MenuAutoComplete", ReplyAction="http://tempuri.org/IService1/MenuAutoCompleteResponse")]
        System.Threading.Tasks.Task<TryItPages.spoonacularService.Recipe> MenuAutoCompleteAsync(string query);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItPages.spoonacularService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItPages.spoonacularService.IService1>, TryItPages.spoonacularService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TryItPages.spoonacularService.Recipe[] SearchRecipesByIngredients(string ingredients) {
            return base.Channel.SearchRecipesByIngredients(ingredients);
        }
        
        public System.Threading.Tasks.Task<TryItPages.spoonacularService.Recipe[]> SearchRecipesByIngredientsAsync(string ingredients) {
            return base.Channel.SearchRecipesByIngredientsAsync(ingredients);
        }
        
        public TryItPages.spoonacularService.Recipe GetRecipeSummaryById(int id) {
            return base.Channel.GetRecipeSummaryById(id);
        }
        
        public System.Threading.Tasks.Task<TryItPages.spoonacularService.Recipe> GetRecipeSummaryByIdAsync(int id) {
            return base.Channel.GetRecipeSummaryByIdAsync(id);
        }
        
        public TryItPages.spoonacularService.Recipe MenuAutoComplete(string query) {
            return base.Channel.MenuAutoComplete(query);
        }
        
        public System.Threading.Tasks.Task<TryItPages.spoonacularService.Recipe> MenuAutoCompleteAsync(string query) {
            return base.Channel.MenuAutoCompleteAsync(query);
        }
    }
}
